#ifndef LED_MAP_H
#define LED_MAP_H

#define RAIND_START 8
#define RAIND_END 0


#define RAINE_START 8
#define RAINE_END   16


#define RAINF_START 24
#define RAINF_END 16


#define STORMD_START 32
#define STORMD_END   24 


#define STORME_START 32 
#define STORME_END   40 


#define STORMF_START 48 
#define STORMF_END   40 


#define PHOSPHORUS_FLOWA_START 102
#define PHOSPHORUS_FLOWA_END 48

#define PHOSPHORUS_FLOWB_START 102
#define PHOSPHORUS_FLOWB_END 136

#define PHOSPHORUS_RING_START 136
#define PHOSPHORUS_RING_END 226


#define SALT_FLOWA_START 363
#define SALT_FLOWA_END 316

#define SALT_FLOWB_START 363
#define SALT_FLOWB_END 416

#define SALT_RING_START 226
#define SALT_RING_END 316


#define RAINA_START 424
#define RAINA_END 416

#define RAINB_START 424
#define RAINB_END 432

#define RAINC_START 440
#define RAINC_END 432


#define STORMA_START 440
#define STORMA_END 448

#define STORMB_START 456
#define STORMB_END 448

#define STORMC_START 456
#define STORMC_END 464


#define SEDIMENT_RING_START 464
#define SEDIMENT_RING_END 554

#define SEDIMENT_FLOWA_START 554
#define SEDIMENT_FLOWA_END 608

#define SEDIMENT_FLOWB_START 644
#define SEDIMENT_FLOWB_END 608


#define TRASH_RING_START 644
#define TRASH_RING_END 734

#define TRASH_FLOWA_START 778
#define TRASH_FLOWA_END 734

#define TRASH_FLOWB_START 778
#define TRASH_FLOWB_END 834


int _length(int start, int end);
int _addr(int start, int end, int idx);


#endif
